apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  namespace: flink-jobs
  name: basic-example-1
spec:
  image: pull flink:1.19.0-java11
  flinkVersion: v1_19
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "1"
    state.savepoints.dir: s3://test/savepoins
    state.checkpoints.dir: s3://test/checkpoints
    s3.endpoint: http://minio-svc.minio-dev:9000
    s3.path.style.access: "true"
    s3.access-key: minioadmin
    s3.secret-key: minioadmin
  ingress:
    template: "/{{namespace}}/{{name}}(/|$)(.*)"
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: "/$2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "1024m"
      cpu: 0.5
  taskManager:
    resource:
      memory: "1024m"
      cpu: 0.5
  job:
    jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
    parallelism: 1
    state: running
