apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  labels:
    app: kafka-ui
spec:
  type: NodePort # or use LoadBalancer if running on a cloud provider
  ports:
    - port: 3001
      targetPort: 8080 # Change this to the port Kafka UI is running on
      protocol: TCP
      name: http
  selector:
    app: kafka-ui # This should match the label of your Kafka UI pods
