yamlApplicationConfig:
  kafka:
    clusters:
      - name: yaml
        bootstrapServers: cluster-01-kafka-bootstrap.kafka.svc.cluster.local:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false
